export enum  actionTypes{
   CHANGE_THE_NAME,
   SET_NOT_UNIQUE_NAME_STATUS,
   SET_UNIQUE_NAME_STATUS,
   CHECK_UNIQUE_USER_NAME,
   START_SIGNUP_PROCESSING,
   STOP_SIGNUP_PROCESSING,
   SET_NOTIFICATION,
   START_LOGIN_PROCESS,
   STOP_LOGIN_PROCESS
}